<?php

acf_add_local_field_group([
    'key'                   => 'group_5901bcdf059cd',
    'title'                 => 'Default Template',
    'fields'                => [
        [
            'key' => 'field_contact_us_group_key',
            'label' => 'Contact us',
            'name' => 'contact_us',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => [
                'width' => '',
                'class' => '',
                'id' => '',
            ],
            'layout' => 'block',
            'sub_fields' => [
                [
                    'key' => 'field_contact_us_text_key',
                    'label' => 'Text',
                    'name' => 'text',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'default_value' => 'Contact us to learn more about OroCommerce\'s capabilities',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ],
                [
                    'key' => 'field_contact_us_page_key',
                    'label' => 'Select page',
                    'name' => 'select_page',
                    'type' => 'post_object',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'post_type' => [
                        0 => 'page',
                    ],
                    'taxonomy' => '',
                    'allow_null' => 0,
                    'multiple' => 0,
                    'return_format' => 'id',
                    'ui' => 1,
                ],
                [
                    'key' => 'field_contact_us_page_banner_title',
                    'label' => 'Link Title',
                    'name' => 'link_title',
                    'type' => 'text',
                ],
            ],
        ],
        [
            'key'               => 'field_620e43cab76fc',
            'label'             => 'Blog Title',
            'name'              => 'blog_title',
            'type'              => 'text',
            'instructions'      => '',
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => [
                'width' => '',
                'class' => '',
                'id'    => '',
            ],
            'default_value'     => '',
            'placeholder'       => '',
            'prepend'           => '',
            'append'            => '',
            'maxlength'         => '',
        ],
        [
            'key'               => 'field_5901bd05a8af4',
            'label'             => 'Sub Title',
            'name'              => 'sub_title',
            'type'              => 'textarea',
            'instructions'      => '',
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => [
                'width' => '',
                'class' => '',
                'id'    => '',
            ],
            'default_value'     => '',
            'placeholder'       => '',
            'maxlength'         => '',
            'rows'              => '',
            'new_lines'         => 'wpautop',
        ],
        [
            'key' => 'field_subscribe_key',
            'label' => 'Subscribe',
            'name' => 'subscribe_block',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => [
                'width' => '',
                'class' => '',
                'id' => '',
            ],
            'layout' => 'block',
            'sub_fields' => [
                [
                    'key'               => 'field_subscribe_title_key',
                    'label'             => 'Subscribe Title',
                    'name'              => 'subscribe_title',
                    'type'              => 'text',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => [
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ],
                    'default_value'     => 'Join our Blog Digest',
                    'placeholder'       => '',
                    'prepend'           => '',
                    'append'            => '',
                    'maxlength'         => '',
                ],
                [
                    'key'               => 'field_subscribe_text_key',
                    'label'             => 'Subscribe Text',
                    'name'              => 'subscribe_text',
                    'type'              => 'text',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => [
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ],
                    'default_value'     => 'Stay up to date with the latest news. Sign up for a regular email newsletter',
                    'placeholder'       => '',
                    'prepend'           => '',
                    'append'            => '',
                    'maxlength'         => '',
                ],
            ],
        ],
        [
            'key' => 'field_contribute_key',
            'label' => 'Contribute',
            'name' => 'contribute',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => [
                'width' => '',
                'class' => '',
                'id' => '',
            ],
            'layout' => 'block',
            'sub_fields' => [
                [
                    'key' => 'field_contribute_text_key',
                    'label' => 'Text',
                    'name' => 'text',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'default_value' => 'Contribute to Oro’s blog',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ],
                [
                    'key' => 'field_contribute_link_key',
                    'label' => 'Select page',
                    'name' => 'select_page',
                    'type' => 'post_object',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'post_type' => [
                        0 => 'page',
                    ],
                    'taxonomy' => '',
                    'allow_null' => 0,
                    'multiple' => 0,
                    'return_format' => 'id',
                    'ui' => 1,
                ],
            ],
        ],
        [
            'key' => 'field_single_post_bottom_banner_key',
            'label' => 'Single Post Bottom Banner',
            'name' => 'sp_post_bottom_banner',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => [
                'width' => '',
                'class' => '',
                'id' => '',
            ],
            'layout' => 'block',
            'sub_fields' => [
                [
                    'key' => 'field_sp_bottom_text_key',
                    'label' => 'Text',
                    'name' => 'text',
                    'type' => 'text',
                ],
                [
                    'key' => 'field_sp_bottom_page_key',
                    'label' => 'Select link',
                    'name' => 'select_page',
                    'type' => 'link',
                ],
                [
                    'key' => 'field_sp_bottom_image_key',
                    'label' => 'Image',
                    'name' => 'image',
                    'type' => 'image',
                    'return_format' => 'id',
                    'preview_size' => 'medium'
                ],
            ],
        ],
    ],
    'location' => [
        [
            [
                'param'    => 'page_type',
                'operator' => '==',
                'value'    => 'posts_page',
            ],
        ],
    ],
    'menu_order'            => 0,
    'position'              => 'normal',
    'style'                 => 'default',
    'label_placement'       => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen'        => '',
    'active'                => 1,
    'description'           => '',
]);
